name: ActriumGraves
main: xyz.actrium.graves.ActriumGraves
description: ActriumGraves is a plugin that allows players to spawn a grave when they die that can be picked back up.
author: Skitbet
version: 1.2.2
api-version: 1.13
commands:
  grave:
    description: Main command for ActriumGraves
  actriumgraves:
    description: Information about the ActriumGraves plugin.